Fix/2 data binding
jonsmithers/promise-dialog pull request #3
Opened 2017-04-24 18:44 UTC by jonsmithers

Fixes #2 to allow for data binding to `promise-value`.

2017-04-24 20:06 UTC, billy-hardy commented on promise-dialog.html
> +                            this.closeAsResolved(target["promise-value"]);
I think this should be `this.closeAsResolved(target["promiseValue"] || target.getAttribute("promise-value"))`

2017-04-24 20:11 UTC, dumbbillyhardy requested changes

2017-04-24 20:11 UTC, billy-hardy commented on test/promise-dialog_test.html
> +            resolveButton['promise-value'] = expected;
I don't think this will account for binding. Isn't the value set in polymer as camelCase?

2017-04-24 20:11 UTC, billy-hardy commented on test/promise-dialog_test.html
> +            resolveButton.setAttribute('promise-value', "this line does nothing");
I think it would be worth while to have a test case that checks for attributes being set

2017-04-24 20:22 UTC, billy-hardy commented on promise-dialog.html
> +                            this.closeAsResolved(target["promise-value"]);
well actually, guess it could just be `target.promiseValue`

2017-04-25 03:51 UTC, jonsmithers commented on promise-dialog.html
> +                            this.closeAsResolved(target["promise-value"]);
yeah....good catch

2017-04-27 21:06 UTC, dumbbillyhardy approved these changes

2017-04-27 21:08 UTC, merged